export const YOU_ARE_NOT_ADMIN = "YOU_ARE_NOT_ADMIN";
export const EMPTY_UID = "EMPTY_UID";
export const ADMIN_UID_EMPTY = "ADMIN_UID_EMPTY";
export const USER_PUBLIC_DATA_NOT_EXISTS = "USER_PUBLIC_DATA_NOT_EXISTS";
export const ADMIN_PUBLIC_DATA_NOT_EXISTS = "ADMIN_PUBLIC_DATA_NOT_EXISTS";
